#region Copyright
////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2018 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 20.62Release
// Tag = production/akw/20.62.00-0-gac8709a
////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile FlyeExerciseName type as a class
    /// </summary>
    public static class FlyeExerciseName 
    {
        public const ushort CableCrossover = 0;
        public const ushort DeclineDumbbellFlye = 1;
        public const ushort DumbbellFlye = 2;
        public const ushort InclineDumbbellFlye = 3;
        public const ushort KettlebellFlye = 4;
        public const ushort KneelingRearFlye = 5;
        public const ushort SingleArmStandingCableReverseFlye = 6;
        public const ushort SwissBallDumbbellFlye = 7;
        public const ushort Invalid = (ushort)0xFFFF;


    }
}

