////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2018 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 20.62Release
// Tag = production/akw/20.62.00-0-gac8709a
////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;
import java.math.BigInteger;


public class VideoClipMesg extends Mesg {

   
   public static final int ClipNumberFieldNum = 0;
   
   public static final int StartTimestampFieldNum = 1;
   
   public static final int StartTimestampMsFieldNum = 2;
   
   public static final int EndTimestampFieldNum = 3;
   
   public static final int EndTimestampMsFieldNum = 4;
   
   public static final int ClipStartFieldNum = 6;
   
   public static final int ClipEndFieldNum = 7;
   
   public static final int TimestampFieldNum = 254;
   
   public static final int DurationFieldNum = 0;
   
   public static final int RepetitionsFieldNum = 3;
   
   public static final int WeightFieldNum = 4;
   
   public static final int SetTypeFieldNum = 5;
   
   public static final int StartTimeFieldNum = 6;
   
   public static final int CategoryFieldNum = 7;
   
   public static final int CategorySubtypeFieldNum = 8;
   
   public static final int WeightDisplayUnitFieldNum = 9;
   
   public static final int MessageIndexFieldNum = 10;
   
   public static final int WktStepIndexFieldNum = 11;
   

   protected static final  Mesg videoClipMesg;
   static {
      // video_clip
      videoClipMesg = new Mesg("video_clip", MesgNum.VIDEO_CLIP);
      videoClipMesg.addField(new Field("clip_number", ClipNumberFieldNum, 132, 1, 0, "", false, Profile.Type.UINT16));
      
      videoClipMesg.addField(new Field("start_timestamp", StartTimestampFieldNum, 134, 1, 0, "", false, Profile.Type.DATE_TIME));
      
      videoClipMesg.addField(new Field("start_timestamp_ms", StartTimestampMsFieldNum, 132, 1, 0, "", false, Profile.Type.UINT16));
      
      videoClipMesg.addField(new Field("end_timestamp", EndTimestampFieldNum, 134, 1, 0, "", false, Profile.Type.DATE_TIME));
      
      videoClipMesg.addField(new Field("end_timestamp_ms", EndTimestampMsFieldNum, 132, 1, 0, "", false, Profile.Type.UINT16));
      
      videoClipMesg.addField(new Field("clip_start", ClipStartFieldNum, 134, 1, 0, "ms", false, Profile.Type.UINT32));
      
      videoClipMesg.addField(new Field("clip_end", ClipEndFieldNum, 134, 1, 0, "ms", false, Profile.Type.UINT32));
      
      videoClipMesg.addField(new Field("timestamp", TimestampFieldNum, 134, 1, 0, "", false, Profile.Type.DATE_TIME));
      
      videoClipMesg.addField(new Field("duration", DurationFieldNum, 134, 1000, 0, "s", false, Profile.Type.UINT32));
      
      videoClipMesg.addField(new Field("repetitions", RepetitionsFieldNum, 132, 1, 0, "", false, Profile.Type.UINT16));
      
      videoClipMesg.addField(new Field("weight", WeightFieldNum, 132, 16, 0, "kg", false, Profile.Type.UINT16));
      
      videoClipMesg.addField(new Field("set_type", SetTypeFieldNum, 2, 1, 0, "", false, Profile.Type.SET_TYPE));
      
      videoClipMesg.addField(new Field("start_time", StartTimeFieldNum, 134, 1, 0, "", false, Profile.Type.DATE_TIME));
      
      videoClipMesg.addField(new Field("category", CategoryFieldNum, 132, 1, 0, "", false, Profile.Type.EXERCISE_CATEGORY));
      
      videoClipMesg.addField(new Field("category_subtype", CategorySubtypeFieldNum, 132, 1, 0, "", false, Profile.Type.UINT16));
      
      videoClipMesg.addField(new Field("weight_display_unit", WeightDisplayUnitFieldNum, 132, 1, 0, "", false, Profile.Type.FIT_BASE_UNIT));
      
      videoClipMesg.addField(new Field("message_index", MessageIndexFieldNum, 132, 1, 0, "", false, Profile.Type.MESSAGE_INDEX));
      
      videoClipMesg.addField(new Field("wkt_step_index", WktStepIndexFieldNum, 132, 1, 0, "", false, Profile.Type.MESSAGE_INDEX));
      
   }

   public VideoClipMesg() {
      super(Factory.createMesg(MesgNum.VIDEO_CLIP));
   }

   public VideoClipMesg(final Mesg mesg) {
      super(mesg);
   }


   /**
    * Get clip_number field
    *
    * @return clip_number
    */
   public Integer getClipNumber() {
      return getFieldIntegerValue(0, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Set clip_number field
    *
    * @param clipNumber
    */
   public void setClipNumber(Integer clipNumber) {
      setFieldValue(0, 0, clipNumber, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Get start_timestamp field
    *
    * @return start_timestamp
    */
   public DateTime getStartTimestamp() {
      return timestampToDateTime(getFieldLongValue(1, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD));
   }

   /**
    * Set start_timestamp field
    *
    * @param startTimestamp
    */
   public void setStartTimestamp(DateTime startTimestamp) {
      setFieldValue(1, 0, startTimestamp.getTimestamp(), Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Get start_timestamp_ms field
    *
    * @return start_timestamp_ms
    */
   public Integer getStartTimestampMs() {
      return getFieldIntegerValue(2, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Set start_timestamp_ms field
    *
    * @param startTimestampMs
    */
   public void setStartTimestampMs(Integer startTimestampMs) {
      setFieldValue(2, 0, startTimestampMs, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Get end_timestamp field
    *
    * @return end_timestamp
    */
   public DateTime getEndTimestamp() {
      return timestampToDateTime(getFieldLongValue(3, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD));
   }

   /**
    * Set end_timestamp field
    *
    * @param endTimestamp
    */
   public void setEndTimestamp(DateTime endTimestamp) {
      setFieldValue(3, 0, endTimestamp.getTimestamp(), Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Get end_timestamp_ms field
    *
    * @return end_timestamp_ms
    */
   public Integer getEndTimestampMs() {
      return getFieldIntegerValue(4, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Set end_timestamp_ms field
    *
    * @param endTimestampMs
    */
   public void setEndTimestampMs(Integer endTimestampMs) {
      setFieldValue(4, 0, endTimestampMs, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Get clip_start field
    * Units: ms
    * Comment: Start of clip in video time
    *
    * @return clip_start
    */
   public Long getClipStart() {
      return getFieldLongValue(6, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Set clip_start field
    * Units: ms
    * Comment: Start of clip in video time
    *
    * @param clipStart
    */
   public void setClipStart(Long clipStart) {
      setFieldValue(6, 0, clipStart, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Get clip_end field
    * Units: ms
    * Comment: End of clip in video time
    *
    * @return clip_end
    */
   public Long getClipEnd() {
      return getFieldLongValue(7, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Set clip_end field
    * Units: ms
    * Comment: End of clip in video time
    *
    * @param clipEnd
    */
   public void setClipEnd(Long clipEnd) {
      setFieldValue(7, 0, clipEnd, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Get timestamp field
    * Comment: Timestamp of the set
    *
    * @return timestamp
    */
   public DateTime getTimestamp() {
      return timestampToDateTime(getFieldLongValue(254, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD));
   }

   /**
    * Set timestamp field
    * Comment: Timestamp of the set
    *
    * @param timestamp
    */
   public void setTimestamp(DateTime timestamp) {
      setFieldValue(254, 0, timestamp.getTimestamp(), Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Get duration field
    * Units: s
    *
    * @return duration
    */
   public Float getDuration() {
      return getFieldFloatValue(0, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Set duration field
    * Units: s
    *
    * @param duration
    */
   public void setDuration(Float duration) {
      setFieldValue(0, 0, duration, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Get repetitions field
    * Comment: # of repitions of the movement
    *
    * @return repetitions
    */
   public Integer getRepetitions() {
      return getFieldIntegerValue(3, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Set repetitions field
    * Comment: # of repitions of the movement
    *
    * @param repetitions
    */
   public void setRepetitions(Integer repetitions) {
      setFieldValue(3, 0, repetitions, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Get weight field
    * Units: kg
    * Comment: Amount of weight applied for the set
    *
    * @return weight
    */
   public Float getWeight() {
      return getFieldFloatValue(4, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Set weight field
    * Units: kg
    * Comment: Amount of weight applied for the set
    *
    * @param weight
    */
   public void setWeight(Float weight) {
      setFieldValue(4, 0, weight, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Get set_type field
    *
    * @return set_type
    */
   public Short getSetType() {
      return getFieldShortValue(5, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Set set_type field
    *
    * @param setType
    */
   public void setSetType(Short setType) {
      setFieldValue(5, 0, setType, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Get start_time field
    * Comment: Start time of the set
    *
    * @return start_time
    */
   public DateTime getStartTime() {
      return timestampToDateTime(getFieldLongValue(6, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD));
   }

   /**
    * Set start_time field
    * Comment: Start time of the set
    *
    * @param startTime
    */
   public void setStartTime(DateTime startTime) {
      setFieldValue(6, 0, startTime.getTimestamp(), Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   public Integer[] getCategory() {
      
      return getFieldIntegerValues(7, Fit.SUBFIELD_INDEX_MAIN_FIELD);
      
   }

   /**
    * @return number of category
    */
   public int getNumCategory() {
      return getNumFieldValues(7, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Get category field
    *
    * @param index of category
    * @return category
    */
   public Integer getCategory(int index) {
      return getFieldIntegerValue(7, index, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Set category field
    *
    * @param index of category
    * @param category
    */
   public void setCategory(int index, Integer category) {
      setFieldValue(7, index, category, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   public Integer[] getCategorySubtype() {
      
      return getFieldIntegerValues(8, Fit.SUBFIELD_INDEX_MAIN_FIELD);
      
   }

   /**
    * @return number of category_subtype
    */
   public int getNumCategorySubtype() {
      return getNumFieldValues(8, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Get category_subtype field
    * Comment: Based on the associated category, see [category]_exercise_names
    *
    * @param index of category_subtype
    * @return category_subtype
    */
   public Integer getCategorySubtype(int index) {
      return getFieldIntegerValue(8, index, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Set category_subtype field
    * Comment: Based on the associated category, see [category]_exercise_names
    *
    * @param index of category_subtype
    * @param categorySubtype
    */
   public void setCategorySubtype(int index, Integer categorySubtype) {
      setFieldValue(8, index, categorySubtype, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Get weight_display_unit field
    *
    * @return weight_display_unit
    */
   public Integer getWeightDisplayUnit() {
      return getFieldIntegerValue(9, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Set weight_display_unit field
    *
    * @param weightDisplayUnit
    */
   public void setWeightDisplayUnit(Integer weightDisplayUnit) {
      setFieldValue(9, 0, weightDisplayUnit, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Get message_index field
    *
    * @return message_index
    */
   public Integer getMessageIndex() {
      return getFieldIntegerValue(10, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Set message_index field
    *
    * @param messageIndex
    */
   public void setMessageIndex(Integer messageIndex) {
      setFieldValue(10, 0, messageIndex, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Get wkt_step_index field
    *
    * @return wkt_step_index
    */
   public Integer getWktStepIndex() {
      return getFieldIntegerValue(11, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

   /**
    * Set wkt_step_index field
    *
    * @param wktStepIndex
    */
   public void setWktStepIndex(Integer wktStepIndex) {
      setFieldValue(11, 0, wktStepIndex, Fit.SUBFIELD_INDEX_MAIN_FIELD);
   }

}
